plugins:
  - jekyll-feed
  
title: tbwcjw.online
description: "the landing page for projects by tbwcjw"
baseurl: "/"
url: "https://tbwcjw.online"

header_pages:
  - index.md
  - contact.md

style: dark

footer: 'join the <a href="https://discord.gg/T9FtuhHBGN">discord server</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
