title: 'b2a3e8.github.io'
description: "A jekyll theme inspired by linux consoles for hackers, developers and script kiddies."
baseurl: "/"
url: "https://tbwcjw.online"

header_pages:
  - index.md
  - contact.md

style: dark

footer: 'TBA: join our <a href='#'>discord</a> server.'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
