plugins:
  - jekyll-feed
  
title: tbwcjw.online
description: "the landing page for projects by tbwcjw"
baseurl: "/"
url: "https://tbwcjw.online"

header_pages:
  - index.md
  - contact.md

style: dark

footer: '<a href="https://discord.gg/T9FtuhHBGN"><img alt="Discord" src="https://img.shields.io/discord/1326441329902878770?label=join%20our%20discord%20server"></a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
