name: Generate Atom Feed 

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'key.asc'
      - 'mail.png'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install beautifulsoup4

      - name: Generate Atom feed
        run: |
          python rss.py
      
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add atom.xml
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update atom.xml feed [ci skip]"
            git push
          fi
